const tryoutTitle = 'Tryout 1';
const tryoutData = [
    {
        nomor: '1',
        imgUrl: 'https://i.ytimg.com/vi/iWX_nJfwc94/maxresdefault.jpg',
        soal: 'Ini soal 1',
        a: 'Ini jawaban a',
        b: 'Ini jawaban b',
        c: 'Ini jawaban c',
        d: 'Ini jawaban d',
        benar: this.a,
    },
    {
        nomor: '2',
        imgUrl: '#',
        soal: 'Ini soal 2',
        a: 'Ini jawaban a',
        b: 'Ini jawaban b',
        c: 'Ini jawaban c',
        d: 'Ini jawaban d',
        benar: this.b,
    },
    {
        nomor: '3',
        imgUrl: '#',
        soal: 'Ini soal 3',
        a: 'Ini jawaban a',
        b: 'Ini jawaban b',
        c: 'Ini jawaban c',
        d: 'Ini jawaban d',
        benar: this.c,
    },
    {
        nomor: '4',
        imgUrl: '#',
        soal: 'Ini soal 4',
        a: 'Ini jawaban a',
        b: 'Ini jawaban b',
        c: 'Ini jawaban c',
        d: 'Ini jawaban d',
        benar: this.d,
    },
    {
        nomor: '5',
        imgUrl: '#',
        soal: 'Ini soal 5',
        a: 'Ini jawaban a',
        b: 'Ini jawaban b',
        c: 'Ini jawaban c',
        d: 'Ini jawaban d',
        benar: this.c,
    },
    {
        nomor: '6',
        imgUrl: '#',
        soal: 'Ini soal 6',
        a: 'Ini jawaban a',
        b: 'Ini jawaban b',
        c: 'Ini jawaban c',
        d: 'Ini jawaban d',
        benar: this.b,
    },
    {
        nomor: '7',
        imgUrl: '#',
        soal: 'Ini soal 7',
        a: 'Ini jawaban a',
        b: 'Ini jawaban b',
        c: 'Ini jawaban c',
        d: 'Ini jawaban d',
        benar: this.a,
    },
    {
        nomor: '8',
        imgUrl: 'https://www.mdpi.com/applsci/applsci-10-02085/article_deploy/html/images/applsci-10-02085-g001.png',
        soal: 'Ini soal 8',
        a: 'Ini jawaban a',
        b: 'Ini jawaban b',
        c: 'Ini jawaban c',
        d: 'Ini jawaban d',
        benar: this.b,
    },
    {
        nomor: '9',
        imgUrl: '#',
        soal: 'Ini soal 9',
        a: 'Ini jawaban a',
        b: 'Ini jawaban b',
        c: 'Ini jawaban c',
        d: 'Ini jawaban d',
        benar: this.c,
    },
    {
        nomor: '10',
        imgUrl: 'https://image2.slideserve.com/5364043/unsteady-heat-transfer-in-semi-infinite-solids-n.jpg#',
        soal: 'Ini soal 10',
        a: 'Ini jawaban a',
        b: 'Ini jawaban b',
        c: 'Ini jawaban c',
        d: 'Ini jawaban d',
        benar: this.d,
    },
];
